#!/bin/bash

# Django static files
python /var/www/apps/messierbingo/manage.py collectstatic --noinput
python /var/www/apps/messierbingo/manage.py migrate --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
